language: go

go:
  - master # This uses automatically the latest version of go

install:
  - mkdir -p ~/go/src/golang.org/x
  - cd ~/go/src/golang.org/x
  - git clone https://github.com/golang/sync.git
  # go get -v github.com/gohugoio/hugo
  - go get -v github.com/spf13/hugo # This provides the latest version of Hugo to Travis CI

script:
  - hugo # This commands builds your website on travis

deploy:
  local_dir: public # Default static site output dir for Hugo
  repo: kid728/kid728.github.io # This is the slug of the repo you want to deploy your site to
  target_branch: master # GitHub pages branch to deploy to (in other cases it can be gh-pages)
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # This is the authentication which you will setup in the next step in travis-ci dashboard
  # email: 632835699@qq.com
  name: kid728
  on:
    branch: master
